name: Generate latest builds
on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master", "dev*"]

jobs:
  run_pytest:
    name: HiCT Library autotests
    runs-on: [ "ubuntu-latest" ]

    steps:
    - name: Checkout sources
      uses: actions/checkout@v3
      with:
        submodules: recursive
    - name: Setup Python
      uses: actions/setup-python@v4.3.1
      with:
        # Version range or exact version of Python or PyPy to use, using SemVer's version range syntax. Reads from .python-version if unset.
        python-version: '>= 3.10'
        # Used to specify a package manager for caching in the default directory. Supported values: pip, pipenv, poetry.
        cache: pip
        # The target architecture (x86, x64) of the Python or PyPy interpreter.
        architecture: x64
        # Set this option if you want the action to check for the latest available version that satisfies the version spec.
        check-latest: true
        # Set this option if you want the action to update environment variables.
        update-environment: true
    - name: Install HDF5 library
      uses: awalsh128/cache-apt-pkgs-action@latest
      with:
        packages: libhdf5-dev
    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        pip install -r requirements-dev.txt
    - name: Install dependencies
      run: |
        pip install pylint
    - name: Analysing the code with pylint
      run: |
        pylint $(git ls-files '*.py')
    - name: Analysing the code with mypy
      run: |
        mypy -m hict
    - name: Launch PyTest
      run: pytest -v .
      
